"""Build data/rules/business_rules.xlsx — the sample workbook that proves
the Excel-driven layer. Deterministic output so the artifact is auditable and
regenerable; the committed .xlsx is what the tests read.

Run: .venv/Scripts/python.exe scripts/generate_rules_workbook.py
"""

from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Font

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "data" / "rules" / "business_rules.xlsx"

HEADERS = [
    "Test ID",
    "Source Table",
    "Source Column(s)",
    "Target Table",
    "Target Column",
    "Rule Type",
    "Transformation Logic",
    "Expected",
    "Severity",
    "Where Clause",
    "Key Column",
    "Enabled",
]

# Mirrors the contract-derived rules so both layers check the same truth.
# ER-105 exercises a join across two source files; ER-107 is deliberately
# disabled (proves Enabled=no is skipped); ER-108 is LOW (report-only).
RULES = [
    [
        "ER-001",
        "",
        "",
        "address_pilot",
        "address2",
        "MAX_LENGTH",
        "",
        "67",
        "HIGH",
        "",
        "address_id",
        "yes",
    ],
    [
        "ER-002",
        "address_extract",
        "address2",
        "address_pilot",
        "address2",
        "NULL_CHECK",
        "",
        "",
        "HIGH",
        "",
        "address_id",
        "yes",
    ],
    [
        "ER-003",
        "customer",
        "country",
        "customer",
        "country",
        "UPPERCASE",
        "upper({country})",
        "",
        "HIGH",
        "",
        "customer_id",
        "yes",
    ],
    [
        "ER-004",
        "customer",
        "email",
        "customer",
        "email",
        "LOWERCASE",
        "lower({email})",
        "",
        "HIGH",
        "",
        "customer_id",
        "yes",
    ],
    [
        "ER-005",
        "account_extract,account_codes",
        "branch_code,acct_seq",
        "account_loan",
        "loan_account",
        "CONCAT",
        "{branch_code}|{acct_seq}",
        "",
        "HIGH",
        "",
        "acct_seq=account_seq",
        "yes",
    ],
    [
        "ER-006",
        "account_extract",
        "prod_code",
        "account_loan",
        "product_name",
        "MAP",
        "map(prod_code, products)",
        "",
        "HIGH",
        "",
        "acct_seq=account_seq",
        "yes",
    ],
    [
        "ER-007",
        "customer",
        "status",
        "customer",
        "status",
        "DIRECT_COMPARE",
        "",
        "",
        "MEDIUM",
        "",
        "customer_id",
        "yes",
    ],
    [
        "ER-008",
        "customer",
        "balance",
        "customer",
        "balance",
        "NULL_CHECK",
        "",
        "",
        "LOW",
        "status = 'active'",
        "customer_id",
        "no",
    ],
    [
        "ER-009",
        "address_extract",
        "address1",
        "address_pilot",
        "address1",
        "MAX_LENGTH",
        "",
        "100",
        "LOW",
        "",
        "address_id",
        "yes",
    ],
    # transform_lab: one rule per remaining rule type. ER-112/117/118 also
    # show the three special evaluation modes (inverse target-side transform,
    # SQL-side predicate, sandboxed Python over source columns).
    [
        "ER-101",
        "transform_lab",
        "card_no",
        "transform_lab",
        "card_tail",
        "MIN_LENGTH",
        "",
        "4",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-102",
        "transform_lab",
        "full_name_raw",
        "transform_lab",
        "name",
        "TRIM",
        "strip({full_name_raw})",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-103",
        "",
        "",
        "transform_lab",
        "dob_fmt",
        "DATE_FORMAT",
        "",
        "%d/%m/%Y",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-104",
        "transform_lab",
        "dob_iso",
        "transform_lab",
        "dob_fmt",
        "DATE_TRANSFORM",
        "date_fmt(dob_iso, '%d/%m/%Y')",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-105",
        "transform_lab",
        "unit_price",
        "transform_lab",
        "price_rounded",
        "NUMERIC_ROUND",
        "round(unit_price, 2)",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-106",
        "transform_lab",
        "region_code",
        "transform_lab",
        "region_default",
        "DEFAULT_VALUE",
        "ifnull(region_code, 'GLOBAL')",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-107",
        "transform_lab,country_ref",
        "country",
        "transform_lab",
        "region",
        "LOOKUP",
        "lookup(region)",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-108",
        "",
        "",
        "transform_lab",
        "card_tail",
        "REGEX",
        "",
        r"^\d{4}$",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-109",
        "transform_lab",
        "card_no",
        "transform_lab",
        "card_mask",
        "MASK",
        "mask(card_no)",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-110",
        "transform_lab",
        "ssn",
        "transform_lab",
        "ssn_hash",
        "HASH",
        "sha256(ssn)",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-111",
        "transform_lab",
        "pin_code",
        "transform_lab",
        "pin_enc",
        "ENCRYPTION",
        "enc(pin_code)",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-112",
        "transform_lab",
        "pin_code",
        "transform_lab",
        "pin_enc",
        "DECRYPTION",
        "",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-113",
        "transform_lab",
        "card_no",
        "transform_lab",
        "card_tail",
        "SUBSTRING",
        "substr(card_no, 12, 4)",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-114",
        "transform_lab",
        "prod_ref",
        "transform_lab",
        "code_pref",
        "PREFIX",
        "prefix(prod_ref, 'AC-')",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-115",
        "transform_lab",
        "prod_ref",
        "transform_lab",
        "code_suff",
        "SUFFIX",
        "suffix(prod_ref, '-ZZ')",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-116",
        "transform_lab",
        "flag_yx",
        "transform_lab",
        "flag_label",
        "CASE_WHEN",
        "case(flag_yx) when 'Y' then 'YES' when 'N' then 'NO' else 'OTHER'",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-117",
        "",
        "",
        "transform_lab",
        "card_mask",
        "CUSTOM_SQL",
        "card_mask LIKE '****%'",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-118",
        "transform_lab",
        "qty,pack_size",
        "transform_lab",
        "line_total",
        "CUSTOM_PYTHON",
        "int(qty) * int(pack_size)",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-119",
        "transform_lab",
        "prod_ref",
        "transform_lab",
        "prod_ref_up",
        "UPPERCASE",
        "upper({prod_ref})",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-120",
        "transform_lab",
        "email_addr",
        "transform_lab",
        "email",
        "LOWERCASE",
        "lower({email_addr})",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-121",
        "transform_lab",
        "prod_ref,lab_id",
        "transform_lab",
        "label",
        "CONCAT",
        "{prod_ref}|{lab_id}",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-122",
        "transform_lab",
        "cust_tier",
        "transform_lab",
        "tier_label",
        "MAP",
        "map(cust_tier, tiers)",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-123",
        "transform_lab",
        "qty",
        "transform_lab",
        "qty",
        "DIRECT_COMPARE",
        "",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    [
        "ER-124",
        "transform_lab",
        "pin_code",
        "transform_lab",
        "pin_enc",
        "NULL_CHECK",
        "",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
    # Explicit join: transform_lab.country = region_ref.ctry — the two files
    # name the same key differently, so shared-column auto-join cannot be used.
    [
        "ER-125",
        "transform_lab,region_ref@country=ctry",
        "country",
        "transform_lab",
        "region",
        "LOOKUP",
        "lookup(region)",
        "",
        "HIGH",
        "",
        "lab_id",
        "yes",
    ],
]

MAPPINGS = [
    ("products", "LN", "LOAN"),
    ("products", "FD", "FIXED_DEPOSIT"),
    ("products", "RD", "RECURRING_DEPOSIT"),
    ("statuses", "A", "ACTIVE"),
    ("statuses", "C", "CLOSED"),
    ("statuses", "S", "SUSPENDED"),
    ("tiers", "P", "PLATINUM"),
    ("tiers", "G", "GOLD"),
    ("tiers", "S", "SILVER"),
]


def main():
    wb = Workbook()
    ws = wb.active
    ws.title = "Rules"
    ws.append(HEADERS)
    for row in RULES:
        ws.append(row)
    for c in ws[1]:
        c.font = Font(bold=True)
    for col, width in zip(
        "ABCDEFGHIJKL", [9, 34, 22, 16, 15, 15, 28, 9, 9, 18, 20, 8], strict=False
    ):
        ws.column_dimensions[col].width = width
    ws.freeze_panes = "A2"

    ms = wb.create_sheet("Mapping")
    ms.append(["Mapping Name", "Source Value", "Target Value"])
    for c in ms[1]:
        c.font = Font(bold=True)
    for row in MAPPINGS:
        ms.append(list(row))
    for col, width in zip("ABC", [16, 14, 18], strict=False):
        ms.column_dimensions[col].width = width

    OUT.parent.mkdir(parents=True, exist_ok=True)
    wb.save(OUT)
    print(f"wrote {OUT} ({len(RULES)} rules, {len(MAPPINGS)} mappings)")


if __name__ == "__main__":
    main()
